<?php

namespace AppBundle\Repository;

/**
 * areasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class areasRepository extends \Doctrine\ORM\EntityRepository
{
}
